### PR TITLE
Fixes slides width

### LINKED ISSUE #13: Slide width does not adjust when switching to full-screen mode
## Description

Slide width does not adjust when switching to full-screen mode

## Reproduce

1. Follow jupyterlab-rise's [binder link](https://mybinder.org/v2/gh/jupyterlab-contrib/rise/main?urlpath=lab/tree/examples/README.ipynb)
2. The slides switches automatically to full-screen mode (same if the switch is manual)
3. The slides appears horizontally centered but with their original width
4. Switch to the next page
5. The slides now uses the full width of the screen

## Expected behavior

The slides uses immediately the full width of the screen

## Context

Python package version: jupyterlab-rise 0.1.1

<details><summary>Extension version:</summary>
<pre>
jovyan@jupyter-jupyterlab-2dcontrib-2drise-2d3i1fpld4:~$ jupyter labextension list
JupyterLab v3.6.1
/srv/conda/envs/notebook/share/jupyter/labextensions
        jupyter-offlinenotebook v0.2.2 enabled OK
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyterlab-rise v0.1.0 enabled OK (python, jupyterlab_rise)
        @jupyter-widgets/jupyterlab-manager v5.0.5 enabled OK (python, jupyterlab_widgets)
        @jupyter-server/resource-usage v0.7.0 enabled OK (python, jupyter-resource-usage)

jovyan@jupyter-jupyterlab-2dcontrib-2drise-2d3i1fpld4:~$ jupyter server extension list
Config dir: /home/jovyan/.jupyter

Config dir: /srv/conda/envs/notebook/etc/jupyter
    jupyter_resource_usage enabled
    - Validating jupyter_resource_usage...
      jupyter_resource_usage 0.7.0 OK
    jupyter_server_fileid enabled
    - Validating jupyter_server_fileid...
      jupyter_server_fileid 0.6.0 OK
    jupyter_server_ydoc enabled
    - Validating jupyter_server_ydoc...
      jupyter_server_ydoc 0.6.1 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.6.1 OK
    jupyterlab_rise enabled
    - Validating jupyterlab_rise...
      jupyterlab_rise 0.1.1 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic 0.5.1 OK
    notebook_shim enabled
    - Validating notebook_shim...
      notebook_shim  OK
    jupyter_offlinenotebook enabled
    - Validating jupyter_offlinenotebook...
      jupyter_offlinenotebook  OK

Config dir: /usr/local/etc/jupyter
</pre>
</details>

- Operating System and its version: Ubuntu 22.04
- Browser and its version: Firefox 110 64 bits

<details><summary>Command Line Output</summary>
<pre>
N/A
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>

</pre>
</details>

### PR DESCRIPTION
**Pull request by hbcarlos**
Fixes #13 

It also adds the logic to send log messages from the iframe to the parent window. It is useful in development.

### CODE REVIEW

File: packages/lab/src/index.ts [hunk 1]
```diff
@@ -257,7 +257,7 @@ const plugin: JupyterFrontEndPlugin<IRisePreviewTracker> = {
               !document.fullscreenElement &&
               !iframe.contentDocument?.fullscreenElement
             ) {
-              const goFullScreen = () => {
+              const goFullScreen = async () => {
```
Comment (fcollonval) [inline packages/lab/src/index.ts:260]: Left over from testing?

```suggestion
              const goFullScreen = () => {
```

File: packages/lab/src/preview.ts [hunk 2]
```diff
@@ -63,6 +63,8 @@ export class RisePreview extends DocumentWidget<IFrame, INotebookModel> {
         ]
       })
     });
+    // Uncomment in dev mode to receive logs from the iframe
+    //Private.setupLog();
```
Comment (fcollonval) [inline packages/lab/src/preview.ts:67]: Nice

File: packages/application/src/plugins/rise.ts [hunk 3]
```diff
@@ -1217,3 +1220,49 @@ namespace Rise {
     return reveal_helpstr;
   }
 }
+
+namespace Private {
```
Comment (fcollonval) [inline packages/application/src/plugins/rise.ts:1224]: i was bitten by TypeScript 😜

```suggestion
// @ts-expect-error 'Private' may never be read
namespace Private {
```

**Review by fcollonval — CHANGES_REQUESTED** [review]
Thanks @hbcarlos 

Two small comments; including the one to fix the CI :wink:

**Review by fcollonval — APPROVED** [review]
Thanks @hbcarlos
