### PR TITLE
Fixes running cells and jump to active cell

### LINKED ISSUE #12: Shift-enter in command mode does not execute cells
## Description

Shift-enter in command mode does not execute cells

## Reproduce

1. Follow jupyterlab-rise's [binder link](https://mybinder.org/v2/gh/jupyterlab-contrib/rise/main?urlpath=lab/tree/examples/README.ipynb)
2. Move to a code cell on page 2 while remaining in command-mode
3. Hit <kdb>Shift</kbd>-<kbd>Enter</kbd>

Nothing happens

Note: after entering edit mode,  <kdb>Shift</kbd>-<kbd>Enter</kbd> works as expected.

## Expected behavior

The code cell is executed

## Context

Python package version: jupyterlab-rise 0.1.1

<details><summary>Extension version:</summary>
<pre>
jovyan@jupyter-jupyterlab-2dcontrib-2drise-2d3i1fpld4:~$ jupyter labextension list
JupyterLab v3.6.1
/srv/conda/envs/notebook/share/jupyter/labextensions
        jupyter-offlinenotebook v0.2.2 enabled OK
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyterlab-rise v0.1.0 enabled OK (python, jupyterlab_rise)
        @jupyter-widgets/jupyterlab-manager v5.0.5 enabled OK (python, jupyterlab_widgets)
        @jupyter-server/resource-usage v0.7.0 enabled OK (python, jupyter-resource-usage)

jovyan@jupyter-jupyterlab-2dcontrib-2drise-2d3i1fpld4:~$ jupyter server extension list
Config dir: /home/jovyan/.jupyter

Config dir: /srv/conda/envs/notebook/etc/jupyter
    jupyter_resource_usage enabled
    - Validating jupyter_resource_usage...
      jupyter_resource_usage 0.7.0 OK
    jupyter_server_fileid enabled
    - Validating jupyter_server_fileid...
      jupyter_server_fileid 0.6.0 OK
    jupyter_server_ydoc enabled
    - Validating jupyter_server_ydoc...
      jupyter_server_ydoc 0.6.1 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.6.1 OK
    jupyterlab_rise enabled
    - Validating jupyterlab_rise...
      jupyterlab_rise 0.1.1 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic 0.5.1 OK
    notebook_shim enabled
    - Validating notebook_shim...
      notebook_shim  OK
    jupyter_offlinenotebook enabled
    - Validating jupyter_offlinenotebook...
      jupyter_offlinenotebook  OK

Config dir: /usr/local/etc/jupyter
</pre>
</details>

- Operating System and its version: Ubuntu 22.04
- Browser and its version: Firefox 110 64 bits

<details><summary>Command Line Output</summary>
<pre>
N/A
</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
Activating jupyter-offlinenotebook JupyterLab extension 143.3a0a7be92ffa9c15c416.js:1:882
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jlab_core.3e11c5239452d671150c.js:2:1065413
offline-notebook repoid: https://github.com/jupyterlab-contrib/rise 143.3a0a7be92ffa9c15c416.js:1:1057
offline-notebook repoLabel: GitHub 143.3a0a7be92ffa9c15c416.js:1:1189
offline-notebook binderRefUrl: https://github.com/jupyterlab-contrib/rise/tree/ad010e6b7fde6eb1584b13a15ae647107cc016bb 143.3a0a7be92ffa9c15c416.js:1:1254
offline-notebook binderPersistentUrl: https://mybinder.org/v2/gh/jupyterlab-contrib/rise/ad010e6b7fde6eb1584b13a15ae647107cc016bb 143.3a0a7be92ffa9c15c416.js:1:1329
Language pack 'en_US' not installed! jlab_core.3e11c5239452d671150c.js:2:1274430
Starting application in workspace: "default" jlab_core.3e11c5239452d671150c.js:2:5778
JupyterLab extension jupyterlab-rise is activated! 112.489c482bbad3766cb6f2.js:1:4453
SingleFile is hooking the IntersectionObserver API to detect and load deferred images. single-file-hooks-frames.js:1:531
Starting WebSocket: wss://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels/de636a5c-7901-469b-b013-f96b715e70cd 2 jlab_core.3e11c5239452d671150c.js:2:1025848
Could not find a way to expose utilities_item.js. Check your load order. utilities_item.js:1030:10
No satisfying version (^3.6.1) of shared module @jupyterlab/docregistry found in shared scope default.
Available versions: 3.5.1 from _JUPYTERLAB.CORE_OUTPUT remoteEntry.37bcb12824e081b7dc7e.js:1:5443
Unsatisfied version 1.36.0 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^1.37.1) remoteEntry.37bcb12824e081b7dc7e.js:1:5053
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/translation (required ^3.6.1) remoteEntry.37bcb12824e081b7dc7e.js:1:5053
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/apputils (required ^3.6.1) remoteEntry.37bcb12824e081b7dc7e.js:1:5053
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/ui-components (required ^3.6.1) remoteEntry.37bcb12824e081b7dc7e.js:1:5053
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/settingregistry (required ^3.6.1) remoteEntry.37bcb12824e081b7dc7e.js:1:5053
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/notebook (required ^3.6.1) remoteEntry.37bcb12824e081b7dc7e.js:1:5053
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/application (required ^3.6.1) remoteEntry.37bcb12824e081b7dc7e.js:1:5053
Unsatisfied version 5.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/coreutils (required ^5.6.1) remoteEntry.37bcb12824e081b7dc7e.js:1:5053
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/settingregistry (required ^3.5.2) remoteEntry.d6df56cd69f4640706bc.js:1:6831
Unsatisfied version 6.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/services (required ^6.5.2) remoteEntry.d6df56cd69f4640706bc.js:1:6831
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/translation (required ^3.5.2) remoteEntry.d6df56cd69f4640706bc.js:1:6831
No satisfying version (^3.5.2) of shared module @jupyterlab/outputarea found in shared scope default.
Available versions: 3.5.1 from _JUPYTERLAB.CORE_OUTPUT remoteEntry.d6df56cd69f4640706bc.js:1:7221
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/rendermime (required ^3.5.2) remoteEntry.d6df56cd69f4640706bc.js:1:6831
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/logconsole (required ^3.5.2) remoteEntry.d6df56cd69f4640706bc.js:1:6831
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/mainmenu (required ^3.5.2) remoteEntry.d6df56cd69f4640706bc.js:1:6831
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/notebook (required ^3.5.2) remoteEntry.d6df56cd69f4640706bc.js:1:6831
Unsatisfied version 5.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/coreutils (required ^5.5.2) remoteEntry.2f9a08fa2c9d98922863.js:1:5327
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/statusbar (required ^3.5.2) remoteEntry.2f9a08fa2c9d98922863.js:1:5327
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/notebook (required ^3.5.2) remoteEntry.2f9a08fa2c9d98922863.js:1:5327
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/translation (required ^3.5.2) remoteEntry.2f9a08fa2c9d98922863.js:1:5327
Unsatisfied version 6.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/services (required ^6.5.2) remoteEntry.2f9a08fa2c9d98922863.js:1:5327
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/ui-components (required ^3.5.2) remoteEntry.2f9a08fa2c9d98922863.js:1:5327
Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/apputils (required ^3.5.2) remoteEntry.2f9a08fa2c9d98922863.js:1:5327
Activating jupyter-offlinenotebook JupyterLab extension 143.3a0a7be92ffa9c15c416.js:1:882
Plugin '@jupyter-server/resource-usage:memory-status-item' failed to activate. 6731.bundle.js:2:11699
Error: No provider for: @jupyterlab/statusbar:IStatusBar.
    d https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    u https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    u https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    u https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    u https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    resolveRequiredService https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    n https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    d https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    u https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    u https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    u https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    u https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    activatePlugin https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    r https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    start https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/6731.bundle.js:2
    60880 https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/rise/880.bundle.js:1
6731.bundle.js:2:11751
offline-notebook repoid: https://github.com/jupyterlab-contrib/rise 143.3a0a7be92ffa9c15c416.js:1:1057
offline-notebook repoLabel: GitHub 143.3a0a7be92ffa9c15c416.js:1:1189
offline-notebook binderRefUrl: https://github.com/jupyterlab-contrib/rise/tree/ad010e6b7fde6eb1584b13a15ae647107cc016bb 143.3a0a7be92ffa9c15c416.js:1:1254
offline-notebook binderPersistentUrl: https://mybinder.org/v2/gh/jupyterlab-contrib/rise/ad010e6b7fde6eb1584b13a15ae647107cc016bb 143.3a0a7be92ffa9c15c416.js:1:1329
Language pack 'en_US' not installed! 7819.bundle.js:1:5795
JupyterLab extension jupyterlab-rise is activated! 112.489c482bbad3766cb6f2.js:1:4453
SingleFile is hooking the IntersectionObserver API to detect and load deferred images. single-file-hooks-frames.js:1:531
Convert notebook /examples/README.ipynb to slideshow. 7825.bundle.js:1:4947
The resource from “https://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/rise/examples/static/components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full,Safe&amp;delayStartupUntil=configured” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). README.ipynb
Certains cookies utilisent incorrectement l’attribut recommandé « SameSite » 73
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. README.ipynb
Certains cookies utilisent incorrectement l’attribut recommandé « SameSite » 107
Starting WebSocket: wss://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels/de636a5c-7901-469b-b013-f96b715e70cd 3676.bundle.js:1:17619
Settings failed to load for (@jupyterlab/csvviewer-extension:csv) 
Array [ {…} ]
4030.bundle.js:1:3245
This may happen if {autoStart: false} in (@jupyterlab/csvviewer-extension:csv) or if it is one of the deferredExtensions in page config. 4030.bundle.js:1:3343
Settings failed to load for (@jupyterlab/cell-toolbar-extension:plugin) 
Array [ {…} ]
4030.bundle.js:1:3245
This may happen if {autoStart: false} in (@jupyterlab/cell-toolbar-extension:plugin) or if it is one of the deferredExtensions in page config. 4030.bundle.js:1:3343
Settings failed to load for (@jupyterlab/mainmenu-extension:plugin) 
Array [ {…} ]
4030.bundle.js:1:3245
This may happen if {autoStart: false} in (@jupyterlab/mainmenu-extension:plugin) or if it is one of the deferredExtensions in page config. 4030.bundle.js:1:3343
Settings failed to load for (@jupyterlab/htmlviewer-extension:plugin) 
Array [ {…} ]
4030.bundle.js:1:3245
This may happen if {autoStart: false} in (@jupyterlab/htmlviewer-extension:plugin) or if it is one of the deferredExtensions in page config. 4030.bundle.js:1:3343
Settings failed to load for (@jupyterlab/fileeditor-extension:plugin) 
Array [ {…} ]
4030.bundle.js:1:3245
This may happen if {autoStart: false} in (@jupyterlab/fileeditor-extension:plugin) or if it is one of the deferredExtensions in page config. 4030.bundle.js:1:3343
Settings failed to load for (@jupyterlab/filebrowser-extension:widget) 
Array [ {…} ]
4030.bundle.js:1:3245
This may happen if {autoStart: false} in (@jupyterlab/filebrowser-extension:widget) or if it is one of the deferredExtensions in page config. 4030.bundle.js:1:3343
Settings failed to load for (@jupyterlab/csvviewer-extension:tsv) 
Array [ {…} ]
4030.bundle.js:1:3245
This may happen if {autoStart: false} in (@jupyterlab/csvviewer-extension:tsv) or if it is one of the deferredExtensions in page config. 4030.bundle.js:1:3343
Comm not found for comm id ac357dbd-f760-4cdc-828a-48ad647fb5f6 jlab_core.3e11c5239452d671150c.js:2:1037513
Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early 150.b0e841b75317744a7595.js:1:5783
XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/sessions?1676567748652
[HTTP/2 200 OK 115ms]

Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:283:23
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:639:29
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:1388:31
Error in parsing value for ‘-webkit-transition-duration’.  Declaration dropped. README.ipynb:1530:31
Error in parsing value for ‘transition-duration’.  Declaration dropped. README.ipynb:1531:31
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1590:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1591:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1608:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1609:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1852:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1853:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1868:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1869:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1889:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1890:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1905:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1906:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1926:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1927:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1942:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1943:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1963:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1964:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1979:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1980:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:2005:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:2006:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:2023:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:2024:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:2049:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:2050:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:2067:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:2068:32
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2280:28
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2283:28
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. README.ipynb:2291:28
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:2575:25
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:2641:25
Ruleset ignored due to bad selector. README.ipynb:2796:72
Ruleset ignored due to bad selector. README.ipynb:2813:84
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2869:26
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2872:26
Ruleset ignored due to bad selector. README.ipynb:2918:35
Ruleset ignored due to bad selector. README.ipynb:2923:35
Ruleset ignored due to bad selector. README.ipynb:2928:35
Ruleset ignored due to bad selector. README.ipynb:2936:37
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2971:38
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2973:38
Ruleset ignored due to bad selector. README.ipynb:2995:47
Ruleset ignored due to bad selector. README.ipynb:2997:47
Ruleset ignored due to bad selector. README.ipynb:3001:47
Ruleset ignored due to bad selector. README.ipynb:3006:47
Ruleset ignored due to bad selector. README.ipynb:3012:49
Ruleset ignored due to bad selector. README.ipynb:3014:46
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:3132:31
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3309:14
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3312:14
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3364:26
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3366:26
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. README.ipynb:3477:14
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3496:34
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3498:34
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. README.ipynb:4002:27
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:4045:27
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:4257:27
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:4267:27
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:4278:29
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:5905:29
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:5939:31
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6235:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6236:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6247:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6248:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6331:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6332:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6351:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6352:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6371:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6372:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6391:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6392:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6473:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6474:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6493:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6494:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6513:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6514:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6533:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6534:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6649:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6650:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6665:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6666:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6696:34
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6697:34
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6712:34
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6713:34
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6766:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6767:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6778:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6779:30
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:7257:25
Error in parsing value for ‘-webkit-transform’.  Declaration dropped. README.ipynb:7272:34
Error in parsing value for ‘transform’.  Declaration dropped. README.ipynb:7273:34
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:7361:25
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:7569:29
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:7660:27
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:7724:47
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:7726:47
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:7759:20
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:7762:20
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:7792:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:7793:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:7808:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:7809:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:7826:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:7827:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:8058:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:8059:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:8074:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:8075:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:21:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:22:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:39:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:40:30
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:51:23
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:5:54
Error in parsing value for ‘overflow’.  Declaration dropped. README.ipynb:78:13
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:121:26
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:56:23
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:67:23
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:56:23
Ruleset ignored due to bad selector. README.ipynb:48:61
Ruleset ignored due to bad selector. README.ipynb:55:61
Ruleset ignored due to bad selector. README.ipynb:84:51
Ruleset ignored due to bad selector. README.ipynb:90:51
Ruleset ignored due to bad selector. README.ipynb:108:45
Ruleset ignored due to bad selector. README.ipynb:113:45
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:186:23
Unknown property ‘-moz-border-radius’.  Declaration dropped. README.ipynb:244:22
Error in parsing value for ‘left’.  Declaration dropped. README.ipynb:86:9
Error in parsing value for ‘top’.  Declaration dropped. README.ipynb:87:8
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:231:23
Expected color but found ‘none’.  Error in parsing value for ‘background-color’.  Declaration dropped. README.ipynb:94:21
Error in parsing value for ‘content’.  Declaration dropped. README.ipynb:1:174
Ruleset ignored due to bad selector. README.ipynb:1:1318
Error in parsing value for ‘display’.  Declaration dropped. README.ipynb:1:2750
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:11:27
Unknown property ‘-moz-box-shadow’.  Declaration dropped. README.ipynb:504:19
Unknown property ‘-moz-border-radius’.  Declaration dropped. examples:1:94
Unknown property ‘-moz-box-shadow’.  Declaration dropped. examples:1:217
Unknown property ‘-moz-border-radius’.  Declaration dropped. examples:2:195
Unknown property ‘-moz-border-radius’.  Declaration dropped. examples:1:478
Unknown property ‘-moz-box-shadow’.  Declaration dropped. examples:1:607
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. examples:1:681
Unknown property ‘-moz-border-radius’.  Declaration dropped. examples:3:430
Unknown property ‘-moz-box-shadow’.  Declaration dropped. examples:3:557
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. examples:3:631
Unknown property ‘-moz-border-radius’.  Declaration dropped. examples:21:174
Unknown property ‘-moz-border-radius’.  Declaration dropped. examples:22:156
Unknown property ‘-moz-box-shadow’.  Declaration dropped. examples:1:557
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. examples:1:629
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. examples:2:203
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. examples:4:178
Error in parsing value for ‘vertical-align’.  Declaration dropped. examples:54:42
Unknown property ‘-moz-box-shadow’.  Declaration dropped. examples:5:185
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. examples:5:255
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped. examples:26:80
Error in parsing value for ‘vertical-align’.  Declaration dropped. examples:30:36
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:283:23
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:638:29
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:1387:31
Error in parsing value for ‘-webkit-transition-duration’.  Declaration dropped. README.ipynb:1529:31
Error in parsing value for ‘transition-duration’.  Declaration dropped. README.ipynb:1530:31
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1587:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1588:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1605:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1606:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1863:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1864:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1879:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1880:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1900:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1901:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1916:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1917:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1937:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1938:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1953:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1954:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1974:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1975:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:1990:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:1991:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:2016:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:2017:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:2034:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:2035:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:2060:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:2061:32
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:2078:32
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:2079:32
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2291:28
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2294:28
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. README.ipynb:2302:28
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:2586:25
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:2652:25
Ruleset ignored due to bad selector. README.ipynb:2807:72
Ruleset ignored due to bad selector. README.ipynb:2824:84
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2880:26
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2883:26
Ruleset ignored due to bad selector. README.ipynb:2929:35
Ruleset ignored due to bad selector. README.ipynb:2934:35
Ruleset ignored due to bad selector. README.ipynb:2939:35
Ruleset ignored due to bad selector. README.ipynb:2947:37
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2982:38
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:2984:38
Ruleset ignored due to bad selector. README.ipynb:3006:47
Ruleset ignored due to bad selector. README.ipynb:3008:47
Ruleset ignored due to bad selector. README.ipynb:3012:47
Ruleset ignored due to bad selector. README.ipynb:3017:47
Ruleset ignored due to bad selector. README.ipynb:3023:49
Ruleset ignored due to bad selector. README.ipynb:3025:46
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:3157:31
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3334:14
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3337:14
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3389:26
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3391:26
Unknown pseudo-class or pseudo-element ‘-ms-clear’.  Ruleset ignored due to bad selector. README.ipynb:3502:14
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3521:34
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:3523:34
Unknown pseudo-class or pseudo-element ‘-ms-expand’.  Ruleset ignored due to bad selector. README.ipynb:4027:27
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:4070:27
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:4281:27
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:4291:27
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:4302:29
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:5929:29
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:5963:31
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6258:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6259:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6270:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6271:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6354:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6355:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6374:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6375:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6394:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6395:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6414:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6415:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6496:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6497:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6516:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6517:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6536:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6537:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6556:28
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6557:28
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6674:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6675:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6690:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6691:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6721:34
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6722:34
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6737:34
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6738:34
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6795:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6796:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:6807:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:6808:30
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:7284:25
Error in parsing value for ‘-webkit-transform’.  Declaration dropped. README.ipynb:7299:34
Error in parsing value for ‘transform’.  Declaration dropped. README.ipynb:7300:34
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:7388:25
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:7596:29
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:7687:27
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:7751:47
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:7753:47
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:7786:20
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:7789:20
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:7819:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:7820:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:7835:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:7836:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:7853:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:7854:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:8087:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:8088:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:8103:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:8104:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:21:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:22:30
Error in parsing value for ‘-webkit-transition-delay’.  Declaration dropped. README.ipynb:39:30
Error in parsing value for ‘transition-delay’.  Declaration dropped. README.ipynb:40:30
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:51:23
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:5:54
Error in parsing value for ‘overflow’.  Declaration dropped. README.ipynb:78:13
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector. README.ipynb:121:26
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:56:23
Unknown property ‘-moz-outline-radius’.  Declaration dropped. README.ipynb:67:23
Ruleset ignored due to bad selector. README.ipynb:48:61
Ruleset ignored due to bad selector. README.ipynb:55:61
Ruleset ignored due to bad selector. README.ipynb:84:51
Ruleset ignored due to bad selector. README.ipynb:90:51
Ruleset ignored due to bad selector. README.ipynb:108:45
Ruleset ignored due to bad selector. README.ipynb:113:45
Unknown property ‘-moz-border-radius’.  Declaration dropped. README.ipynb:244:22
Unknown property ‘zoom’.  Declaration dropped. README.ipynb:8:41650
Unknown property ‘zoom’.  Declaration dropped. README.ipynb:8:45164
Ruleset ignored due to bad selector. README.ipynb:354:34
Error in parsing value for ‘content’.  Declaration dropped. README.ipynb:1:174
Ruleset ignored due to bad selector. README.ipynb:1:1318
Error in parsing value for ‘display’.  Declaration dropped. README.ipynb:1:2750
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped. README.ipynb:11:27
Unknown property ‘-moz-box-shadow’.  Declaration dropped. README.ipynb:504:19
XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels?1676567751080
[HTTP/2 200 OK 113ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/sessions?1676567751443
[HTTP/2 200 OK 114ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/terminals?1676567751961
[HTTP/2 200 OK 112ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1/kernel_usage/get_usage/de636a5c-7901-469b-b013-f96b715e70cd?1676567752368
[HTTP/2 200 OK 122ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1?1676567752604
[HTTP/2 200 OK 120ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels?1676567752603
[HTTP/2 200 OK 131ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon.ico
[HTTP/2 301 Moved Permanently 0ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/base/images/favicon.ico
[HTTP/2 200 OK 0ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernelspecs?1676567752970
[HTTP/2 200 OK 115ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/contents/examples/README.ipynb?content=0&1676567755711
[HTTP/2 200 OK 115ms]

Last saving performed Thu Feb 16 2023 18:13:46 GMT+0100 (heure normale d’Europe centrale) while the current file seems to have been saved Thu Feb 16 2023 18:15:47 GMT+0100 (heure normale d’Europe centrale) context.js:702:16
XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/contents/examples?content=1&1676567756736
[HTTP/2 200 OK 120ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1/kernel_usage/get_usage/de636a5c-7901-469b-b013-f96b715e70cd?1676567757649
[HTTP/2 200 OK 126ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1?1676567757759
[HTTP/2 200 OK 114ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon.ico
[HTTP/2 301 Moved Permanently 0ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/base/images/favicon.ico
[HTTP/2 200 OK 0ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/sessions?1676567758971
[HTTP/2 200 OK 114ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels?1676567761826
[HTTP/2 200 OK 113ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/sessions?1676567761828
[HTTP/2 200 OK 113ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/terminals?1676567762188
[HTTP/2 200 OK 114ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels?1676567762829
[HTTP/2 200 OK 114ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1/kernel_usage/get_usage/de636a5c-7901-469b-b013-f96b715e70cd?1676567762848
[HTTP/2 200 OK 135ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1?1676567762909
[HTTP/2 200 OK 118ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon.ico
[HTTP/2 301 Moved Permanently 0ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/base/images/favicon.ico
[HTTP/2 200 OK 0ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/contents/examples?content=1&1676567766895
[HTTP/2 200 OK 120ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1/kernel_usage/get_usage/de636a5c-7901-469b-b013-f96b715e70cd?1676567768032
[HTTP/2 200 OK 293ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1?1676567768080
[HTTP/2 200 OK 221ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon.ico
[HTTP/2 301 Moved Permanently 0ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/base/images/favicon.ico
[HTTP/2 200 OK 0ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/sessions?1676567769121
[HTTP/2 200 OK 423ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels?1676567771984
[HTTP/2 200 OK 115ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/sessions?1676567771988
[HTTP/2 200 OK 116ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/terminals?1676567772342
[HTTP/2 200 OK 113ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels?1676567772971
[HTTP/2 200 OK 114ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1?1676567773380
[HTTP/2 200 OK 113ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1/kernel_usage/get_usage/de636a5c-7901-469b-b013-f96b715e70cd?1676567773386
[HTTP/2 200 OK 129ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon.ico
[HTTP/2 301 Moved Permanently 0ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/base/images/favicon.ico
[HTTP/2 200 OK 0ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/contents/examples?content=1&1676567777085
[HTTP/2 200 OK 122ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1?1676567778532
[HTTP/2 200 OK 123ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1/kernel_usage/get_usage/de636a5c-7901-469b-b013-f96b715e70cd?1676567778576
[HTTP/2 200 OK 132ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon.ico
[HTTP/2 301 Moved Permanently 0ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/base/images/favicon.ico
[HTTP/2 200 OK 0ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/sessions?1676567779578
[HTTP/2 200 OK 113ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon-busy-1.ico
[HTTP/2 301 Moved Permanently 113ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon.ico
[HTTP/2 301 Moved Permanently 0ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/base/images/favicon.ico
[HTTP/2 200 OK 0ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels?1676567782193
[HTTP/2 200 OK 115ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/sessions?1676567782196
[HTTP/2 200 OK 116ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/terminals?1676567782580
[HTTP/2 200 OK 115ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels?1676567783116
[HTTP/2 200 OK 114ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1?1676567783836
[HTTP/2 200 OK 115ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1/kernel_usage/get_usage/de636a5c-7901-469b-b013-f96b715e70cd?1676567783848
[HTTP/2 200 OK 127ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon.ico
[HTTP/2 301 Moved Permanently 0ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/base/images/favicon.ico
[HTTP/2 200 OK 0ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/contents/examples?content=1&1676567787293
[HTTP/2 200 OK 120ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1?1676567788986
[HTTP/2 200 OK 113ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1/kernel_usage/get_usage/de636a5c-7901-469b-b013-f96b715e70cd?1676567789037
[HTTP/2 200 OK 130ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon.ico
[HTTP/2 301 Moved Permanently 0ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/base/images/favicon.ico
[HTTP/2 200 OK 0ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/sessions?1676567789787
[HTTP/2 200 OK 114ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels?1676567792390
[HTTP/2 200 OK 111ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/sessions?1676567792395
[HTTP/2 200 OK 571ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/terminals?1676567792729
[HTTP/2 200 OK 121ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/kernels?1676567793263
[HTTP/2 200 OK 112ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1?1676567794248
[HTTP/2 200 OK 114ms]

XHRGEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/api/metrics/v1/kernel_usage/get_usage/de636a5c-7901-469b-b013-f96b715e70cd?1676567794291
[HTTP/2 200 OK 127ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/favicons/favicon.ico
[HTTP/2 301 Moved Permanently 0ms]

GEThttps://hub.gke2.mybinder.org/user/jupyterlab-contrib-rise-3i1fpld4/static/base/images/favicon.ico
[HTTP/2 200 OK 0ms]

</pre>
</details>

### PR DESCRIPTION
**Pull request by hbcarlos**
Fixes #12

### CODE REVIEW

File: packages/application/src/plugins/rise.ts [hunk 1]
```diff
@@ -273,37 +278,21 @@ namespace Rise {
...
-    //   let fragment_div = cell.smart_exec_next_fragment;
-    //   let visible = $(fragment_div).hasClass('visible');
-    //   if (visible) {
-    //     Jupyter.notebook.execute_cell_and_select_below();
-    //   } else {
-    //     Jupyter.notebook.execute_selected_cells();
-    //   }
-    // } else {
-    //   Jupyter.notebook.execute_cell_and_select_below();
-    // }
```
Comment (fcollonval) [inline packages/application/src/plugins/rise.ts:294]: I know it is not great but could you keep that old piece of code as the smart execution feat' is missing and that snippet will likely be useful when restoring it.

**Review by fcollonval — COMMENTED** [review]
Thanks @hbcarlos

I have a minor comment. But not directly related to your code.

**Review by fcollonval — APPROVED** [review]
Thanks @hbcarlos
