### PR TITLE
Fixes focus, initial load, and full screen

### LINKED ISSUE #15: Slides do not react to the usual navigation shortcuts on startup
## Description

Slides do not react to the usual navigation shortcuts on startup

## Reproduce

1. Follow jupyterlab-rise's  [binder link](https://mybinder.org/v2/gh/jupyterlab-contrib/rise/main?urlpath=lab/tree/examples/README.ipynb)
2. Slides appear in full screen
3. The usual shortcuts (space, arrow down, page down, ...) have no effect
4. Clic in a cell
5. Now the shortcuts function as usual

## Expected behavior

The shortcuts would immediately function as usual

## Context

Python package version: jupyterlab-rise 0.1.1

<details><summary>Extension version:</summary>
<pre>
jovyan@jupyter-jupyterlab-2dcontrib-2drise-2d3i1fpld4:~$ jupyter labextension list
JupyterLab v3.6.1
/srv/conda/envs/notebook/share/jupyter/labextensions
        jupyter-offlinenotebook v0.2.2 enabled OK
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyterlab-rise v0.1.0 enabled OK (python, jupyterlab_rise)
        @jupyter-widgets/jupyterlab-manager v5.0.5 enabled OK (python, jupyterlab_widgets)
        @jupyter-server/resource-usage v0.7.0 enabled OK (python, jupyter-resource-usage)

jovyan@jupyter-jupyterlab-2dcontrib-2drise-2d3i1fpld4:~$ jupyter server extension list
Config dir: /home/jovyan/.jupyter

Config dir: /srv/conda/envs/notebook/etc/jupyter
    jupyter_resource_usage enabled
    - Validating jupyter_resource_usage...
      jupyter_resource_usage 0.7.0 OK
    jupyter_server_fileid enabled
    - Validating jupyter_server_fileid...
      jupyter_server_fileid 0.6.0 OK
    jupyter_server_ydoc enabled
    - Validating jupyter_server_ydoc...
      jupyter_server_ydoc 0.6.1 OK
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 3.6.1 OK
    jupyterlab_rise enabled
    - Validating jupyterlab_rise...
      jupyterlab_rise 0.1.1 OK
    nbclassic enabled
    - Validating nbclassic...
      nbclassic 0.5.1 OK
    notebook_shim enabled
    - Validating notebook_shim...
      notebook_shim  OK
    jupyter_offlinenotebook enabled
    - Validating jupyter_offlinenotebook...
      jupyter_offlinenotebook  OK

Config dir: /usr/local/etc/jupyter
</pre>
</details>

- Operating System and its version: Ubuntu 22.04
- Browser and its version: Firefox 110 64 bits

<details><summary>Command Line Output</summary>
<pre>
N/A
</pre>
</details>

### PR DESCRIPTION
**Pull request by hbcarlos**
Fixes #15 

Fixes the inial load of the document, puts the focus on the slide show after loading, and fixes opening in full screen.

### CODE REVIEW

File: packages/lab/src/preview.ts [hunk 1]
```diff
@@ -199,6 +200,29 @@ export class RisePreview extends DocumentWidget<IFrame, INotebookModel> {
...
   }
 
+  private async _waitForIFrame(iframe: HTMLIFrameElement): Promise<boolean> {
+    const ready = new PromiseDelegate<boolean>();
+
+    const setReady = () => {
+      iframe.contentWindow!.removeEventListener('load', setReady);
+
+      const waitForReveal = setInterval(() => {
+        if (iframe.contentDocument!.querySelector('.reveal')) {
```
Comment (fcollonval) [inline packages/lab/src/preview.ts:210]: I would add here the condition that was in the toggle full screen command:

```suggestion
        if (iframe.contentDocument?.readyState === 'complete' && iframe.contentDocument!.querySelector('.reveal')) {
```

File: packages/lab/src/preview.ts [hunk 2]
```diff
@@ -162,31 +166,28 @@ export class RisePreview extends DocumentWidget<IFrame, INotebookModel> {
...
-        iframe.contentWindow!.removeEventListener('load', setReady);
-        const waitForReveal = setInterval(() => {
-          if (iframe.contentDocument!.querySelector('.reveal')) {
-            clearInterval(waitForReveal);
-            this._ready.resolve();
-          }
-        }, 500);
-      };
+  setActiveCellIndex(index: number, reload = true): Promise<void> {
+    const ready = new PromiseDelegate<void>();
```
Comment (fcollonval) [inline packages/lab/src/preview.ts:170]: Let's avoid this.

```suggestion
```

File: packages/lab/src/preview.ts [hunk 3]
```diff
@@ -162,31 +166,28 @@ export class RisePreview extends DocumentWidget<IFrame, INotebookModel> {
...
-      const setReady = () => {
-        iframe.contentWindow!.removeEventListener('load', setReady);
-        const waitForReveal = setInterval(() => {
-          if (iframe.contentDocument!.querySelector('.reveal')) {
-            clearInterval(waitForReveal);
-            this._ready.resolve();
-          }
-        }, 500);
-      };
+  setActiveCellIndex(index: number, reload = true): Promise<void> {
```
Comment (fcollonval) [inline packages/lab/src/preview.ts:169]: To avoid PromiseDelegate

```suggestion
  async setActiveCellIndex(index: number, reload = true): Promise<void> {
```

File: packages/lab/src/preview.ts [hunk 4]
```diff
@@ -162,31 +166,28 @@ export class RisePreview extends DocumentWidget<IFrame, INotebookModel> {
...
+    const ready = new PromiseDelegate<void>();
+    const iframe = this.iframe!;
 
+    if (reload) {
       this.content.url = this.getRiseUrl(this.path, index);
-      iframe.contentWindow!.addEventListener('load', setReady);
+      this._waitForIFrame(iframe)
+        .then(r => ready.resolve())
+        .catch(e => ready.reject(e));
```
Comment (fcollonval) [inline packages/lab/src/preview.ts:177]:
```suggestion
      await this._waitForIFrame(iframe);
```

File: packages/lab/src/preview.ts [hunk 5]
```diff
@@ -162,31 +166,28 @@ export class RisePreview extends DocumentWidget<IFrame, INotebookModel> {
...
           null,
           '',
           this.getRiseUrl(this.path, index)
         );
+        ready.resolve();
       }
+      ready.reject('No content.');
     }
+
+    return ready.promise;
```
Comment (fcollonval) [inline packages/lab/src/preview.ts:190]:
```suggestion
```

File: packages/lab/src/preview.ts [hunk 6]
```diff
@@ -162,31 +166,28 @@ export class RisePreview extends DocumentWidget<IFrame, INotebookModel> {
...
+        .then(r => ready.resolve())
+        .catch(e => ready.reject(e));
     } else {
       if (iframe.contentWindow) {
         iframe.contentWindow.history.pushState(
           null,
           '',
           this.getRiseUrl(this.path, index)
         );
+        ready.resolve();
```
Comment (fcollonval) [inline packages/lab/src/preview.ts:185]:
```suggestion
        return Promise.resolve();
```

File: packages/lab/src/preview.ts [hunk 7]
```diff
@@ -162,31 +166,28 @@ export class RisePreview extends DocumentWidget<IFrame, INotebookModel> {
...
       }
+      ready.reject('No content.');
```
Comment (fcollonval) [inline packages/lab/src/preview.ts:187]:
```suggestion
      return Promise.reject('No content.');
```

File: packages/lab/src/preview.ts [hunk 8]
```diff
@@ -65,9 +65,6 @@ export class RisePreview extends DocumentWidget<IFrame, INotebookModel> {
     });
 
     this._ready = new PromiseDelegate<void>();
-    // `setActiveCellIndex` needs to be called at least once.
```
Comment (fcollonval) [inline packages/lab/src/preview.ts:68]: Thanks for removing my ugly code :wink:

**Review by fcollonval — CHANGES_REQUESTED** [review]
Thanks a lot for the fix @hbcarlos 

I have mainly two comments:
- Code styling in `setActiveCellIndex` to avoid `PromiseDelegate`
- Add an additional condition in `_waitForIFrame`

File: packages/lab/src/preview.ts (hunk 1 above)
Comment (hbcarlos) [reply packages/lab/src/preview.ts:210]: why? The interval is only set once the iframe is ready. We check before calling setReady.

Comment (fcollonval) [reply packages/lab/src/preview.ts:205]: good point I miss that relation ship with the load event.

**Review by fcollonval — APPROVED** [review]
Thanks @hbcarlos
